### ISSUE TITLE
Feature: Enable Going Alone (Chopping)

### ISSUE THREAD

**Issue by justinleebehnke** [justinleebehnke/sheephead2#15]
As a picker, I should have the option to go alone or chop which means that the player with the Jack of Diamonds is NOT my partner.

If I have the Jack of Diamonds, I do not have to announce that I am going alone.

As a player, I should be able to see that the picker has chopped.

**Comment by justinleebehnke** [comment]
Question for @Econgineer, 

I am planning on saying that the option to chop should be offered to the picker AFTER they have picked up the blind.

So basically at the moment that you would click "BURY" after you as the picker has selected the cards to bury, there should be another option that effectively says "BURY & CHOP" or something like that.

To me that is the moment when it has to be decided whether the picker will be going alone. It's after the blind has been placed in their hand but before the first card of the first trick has been played. Which is at the same moment in time as the bury. 

Do you agree?

**Comment by Econgineer** [comment]
You are correct. Chop announcement has to occur before the bury. Once you bury the first player can lay the first card and you can't go back
