### ISSUE TITLE
FEATURE: Track Net Earnings Hand over Hand for a given session

### ISSUE THREAD

**Issue by justinleebehnke** [justinleebehnke/sheephead2#34]
Every time the end or hand report appears:

It should state how much each player netted for the hand that they just completed and how much each player has netted for the current session. By "current session", I mean everything that has happened from the moment that the host pressed the "Start Game" button.

The report should be something like:

| Player | Earnings for Hand | Total Earnings |
|--------|---------------|------------------|
| Jake   | -$0.50        | +$9.25           |
| Jesse  | -$0.50        | +$14.50          |
| Justin | +$0.50        | -$26.25          |
| John   | +$0.50        | -$2.50           |

The sum of the "Hand Earnings" should always be zero. The sum for the Session Earnings should also always be zero. All money is being exchanged between the players in the session and all players start with Net Earnings of $0.00 at the beginning of the session.

Here is the logic for how the payments work as I understand it.

  | Losing as member of Opposition (2 on 2) | Losing as member of the opposition (3 on 1) | Losing as member of Picking Team (2 on 2) | Losing as Picker who Chopped (3 on 1)
-- | -- | -- | -- | --
Got at least 30 points | $0.25 per player to picking team | $0.75 each player to Picker | $0.75 per player to opposition | $0.75 per player to opposition
Got at least one trick | $0.50 per player to picking team | $1.50 each player to Picker | $1.50 per player to opposition | $1.50 per player to opposition
Didn't get even one trick | $0.75 per player to picking team | $2.25 each player to Picker | $2.25 per player to opposition | $3.25 per player to opposition

Whatever the final price ends up being if the hand is a hand of doubles then multiply all of the netted earnings by two (be sure to decrement the remaining number of hands of doubles to be played)

@Econgineer please review and comment to either confirm that this is correct or to correct whatever mistakes I have made. Thank you!

**Comment by Econgineer** [comment]
I've cleaned up the graphic describing the pay structure. It is consistent with the first two columns of you above table, except that one needs to get at least 31 points to get schneider.
![image](https://user-images.githubusercontent.com/19895151/113590668-8a522780-95f8-11eb-8918-522fbaaba13d.png)

The above assumes we're playing for quarters, more generally, if we're playing for x's (dollars for example):
![image](https://user-images.githubusercontent.com/19895151/113590786-b077c780-95f8-11eb-98c8-e972885ba11f.png)

**Comment by Econgineer** [comment]
![image](https://user-images.githubusercontent.com/19895151/113591372-6cd18d80-95f9-11eb-984a-497c27953ed5.png)
Updated your table witch chicken scratch...

**Comment by justinleebehnke** [comment]
So the only question I have on the table modification. Isn't it true that in the case of Losing as Picker who Chopped (3 on 1) where they didn't even get one trick, the picker would have to pay an extra dollar on top of the money that they lost? So it seems like rather than $4.50 as you have it there, it should be $5.50 if you include that dollar. 

The follow-up question is if you were in a round of doubles would it be 2 dollars? Or would the extra penalty dollar be added after the doubling of the base pay.

**Comment by justinleebehnke** [comment]
My other question for @Econgineer is when looking at the graphic you made, what is the significance of an open dot vs a closed dot? If any.

**Comment by justinleebehnke** [comment]
> ![image](https://user-images.githubusercontent.com/19895151/113591372-6cd18d80-95f9-11eb-984a-497c27953ed5.png)
> Updated your table witch chicken scratch...

Yesterday John mentioned an interesting rule that if the picker chopped and didn't even win one trick then in addition to the normal base pay of $4.50, another dollar would have to be added on top of that. Did I understand that right?

If so, I thought that the bottom right tile for $4.50 should actually be $5.50.

But that made me wonder about a hand of doubles, would the doubling be applied to the 5.50? or the $4.50 and then a dollar added at the end? (Is it 2 dollars or still just 1 dollar extra in the case of double?)

**Comment by Econgineer** [comment]
The no trick dollar rule applies only to the picker, not his partner. Your team could win, but if the person that picked doesn't get a trick, he owes each of the other players a dollar. I don't think the dollar becomes 2 dollars during doubles. The no trick chop case should be 5.50 after applying this rule,  but I didn't want to further confuse an already complicated topic. Its easy to add the no trick dollar rule over the top after you get the base table working, in the same way you'll apply doubles after the above. (Apply doubles first, the add the dollar,  not the reverse).

Open and closed dots are number line interval notation 
![Screenshot_20210406-031913_Chrome](https://user-images.githubusercontent.com/19895151/113681109-39d5db00-9687-11eb-8b55-f26dd03bac1b.jpg) note that the entire domain 0 to 120 have exactly one payout by looking at the open and closed dots. This removes ambiguity at the edge of the intervals...note the 60-60 case--the closed dot indicates that its connected to the interval that the offense loses. Written another way, that interval is: 
30<score<=60

**Comment by Econgineer** [comment]
Updating the diagram above to more accurately communicate the payment to each player and the totals:
![image](https://user-images.githubusercontent.com/19895151/144075349-b9c4f881-8b4c-41cf-b122-920bc1acd5c0.png)
If you assume $0.25 per point:
![image](https://user-images.githubusercontent.com/19895151/144075507-ad2e939c-c134-4f06-8573-c4ccf3289c29.png)
